apiVersion: /v1
kind: Service
metadata:
  name: control-plane
  namespace: memphis
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: main-traffic
      port: 80
      targetPort: 5555
    - protocol: TCP
      name: client-conn
      port: 6666
      targetPort: 6666
  selector:
    app: memphis-control-plane
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memphis-control-plane
  namespace: memphis
  labels:
    app: memphis-control-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memphis-control-plane
  template:
    metadata:
      name: memphis-control-plane
      labels:
        app: memphis-control-plane
    spec:
      containers:
        - name: memphis-control-plane
          image: 221323242847.dkr.ecr.eu-central-1.amazonaws.com/memphis-control-plane-staging:latest
          ports:
            - containerPort: 5555
              name: main-traffic
            - containerPort: 6666
              name: client-conn
          env:
          - name: ROOT_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: "memphis-creds"
                  key: ROOT_PASSWORD
          - name: CONNECTION_TOKEN
            valueFrom:
                secretKeyRef:
                  name: "memphis-creds"
                  key: CONNECTION_TOKEN